### ISSUE TITLE
How many IMUs do we use

### ISSUE THREAD

**Issue by Rickyhzy** [nsidn98/Gesture-Recognition#2]
I see you're using two IMUS. Are you using both gloves and elbows.  Thank you

**Comment by nsidn98** [comment]
Apologies for the late reply! I did not see this issue earlier. There is a typo in the README. This model just uses one IMU and that is placed on the glove on the back side of the palm. Although I tried using 2 IMUs earlier where I put the second one on the elbow, it didn't improve the performance much, so I stuck with using just one.

Feel free to reopen the issue if you still have any questions
